# Generated by Django 2.0.13 on 2019-05-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('number', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo34x46', models.ImageField(default='Fisher/app/img/logo.jpg', upload_to='Fisher/app/img')),
                ('link_to_insta', models.TextField()),
                ('link_to_facebook', models.TextField()),
                ('link_to_vk', models.TextField()),
                ('main_letter', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_schedule', models.TextField()),
                ('mail', models.TextField()),
                ('phone', models.TextField()),
                ('delivery', models.TextField()),
                ('link_to_insta', models.TextField()),
                ('link_to_facebook', models.TextField()),
                ('link_to_vk', models.TextField()),
                ('rent_rules', models.TextField()),
                ('main_letter', models.TextField()),
                ('logo34x46', models.ImageField(default='Fisher/app/img/logo.jpg', upload_to='Fisher/app/img')),
            ],
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('picture_12x16', models.ImageField(default='Fisher/app/img/icons/logo.png', upload_to='Fisher/app/img/icons')),
                ('button_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HireStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_text_in_frame', models.TextField()),
                ('color_of_frame', models.TextField()),
                ('picture_600x434', models.ImageField(default='Fisher/app/img/items/udilische_600x434.jpg', upload_to='Fisher/app/img/items')),
                ('name', models.TextField()),
                ('stars', models.TextField()),
                ('new_price', models.TextField()),
                ('old_price', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.TextField()),
                ('leaders_of_sale', models.TextField()),
                ('picture_12x16', models.ImageField(default='Fisher/app/img/icons/logo.png', upload_to='Fisher/app/img/icons')),
                ('button_left_text', models.TextField()),
                ('button_right_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeadersStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_text_in_frame', models.TextField()),
                ('color_of_frame', models.TextField()),
                ('picture_600x434', models.ImageField(default='Fisher/app/img/items/udilische_600x434.jpg', upload_to='Fisher/app/img/items')),
                ('name', models.TextField()),
                ('stars', models.TextField()),
                ('new_price', models.TextField()),
                ('old_price', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('add_text_in_frame', models.TextField()),
                ('color_of_frame', models.TextField()),
                ('stars', models.TextField()),
                ('rent_price', models.TextField()),
                ('picture_600x600', models.ImageField(default='Fisher/app/img/items/118ee07b6b6471b0a5e587d09985e6ad.jpg', upload_to='Fisher/app/img/items')),
            ],
        ),
        migrations.CreateModel(
            name='SecondSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('stars', models.TextField()),
                ('new_price', models.TextField()),
                ('old_price', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(default='Fisher/app/img/template.jpg', upload_to='Fisher/app/img')),
                ('picture2', models.ImageField(default='Fisher/app/img/bgHome3.jpg', upload_to='Fisher/app/img')),
                ('picture3', models.ImageField(default='Fisher/app/img/bgHome2.jpg', upload_to='Fisher/app/img')),
                ('headline1', models.TextField()),
                ('headline2', models.TextField()),
                ('headline3', models.TextField()),
                ('link1', models.TextField()),
                ('link2', models.TextField()),
                ('link3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thebigthree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField()),
                ('color1', models.TextField()),
                ('title2', models.TextField()),
                ('color2', models.TextField()),
                ('title3', models.TextField()),
                ('color3', models.TextField()),
                ('picture1', models.ImageField(default='Fisher/app/img/banners/banner1.png', upload_to='Fisher/app/img/banners')),
                ('picture2', models.ImageField(default='Fisher/app/img/banners/banner2.png', upload_to='Fisher/app/img/banners')),
                ('picture3', models.ImageField(default='Fisher/app/img/banners/banner3.png', upload_to='Fisher/app/img/banners')),
            ],
        ),
        migrations.CreateModel(
            name='TheLastThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField()),
                ('title2', models.TextField()),
                ('title3', models.TextField()),
                ('picture1', models.ImageField(default='Fisher/app/img/icons/freeShipping.png', upload_to='Fisher/app/img/icons')),
                ('picture2', models.ImageField(default='Fisher/app/img/icons/freeShipping.png', upload_to='Fisher/app/img/icons')),
                ('picture3', models.ImageField(default='Fisher/app/img/icons/save.png', upload_to='Fisher/app/img/icons')),
            ],
        ),
    ]
