# Generated by Django 2.0.13 on 2019-05-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm1', '0002_contacts_footer_header_hire_hirestaff_leaders_leadersstaff_rent_secondslider_slider_thebigthree_thel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='Fisher/app/img/template.jpg', upload_to='Fisher/app/img'),
        ),
        migrations.AddField(
            model_name='secondslider',
            name='picture_600x600',
            field=models.ImageField(default='Fisher/app/img/items/udilische_600x434.jpg', upload_to='Fisher/app/img/items'),
        ),
    ]
