# Generated by Django 2.0.13 on 2019-05-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm1', '0003_auto_20190531_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thebigthree',
            old_name='color1',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='thebigthree',
            old_name='picture3',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='thebigthree',
            old_name='color2',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='thelastthree',
            old_name='picture1',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='thelastthree',
            old_name='title1',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='thelastthree',
            old_name='title2',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='thebigthree',
            name='color3',
        ),
        migrations.RemoveField(
            model_name='thebigthree',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='thebigthree',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='thebigthree',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='thebigthree',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='thebigthree',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='thelastthree',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='thelastthree',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='thelastthree',
            name='title3',
        ),
        migrations.AddField(
            model_name='footer',
            name='copyrightt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
